Fix PATCH record for TypeError when missing doi
- fix bug where  missing doi raises TypeError
  TypeError: 'NoneType' object is not subscriptable'
- log warning if doi is missing

co-authored-by: "Harri Hirvonsalo" <harri@hirvonsalo.csc.fi>